name: Deploy BookingBite Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "public/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: bookingbite-frontend-prod
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, windows, iis, bookingbite, frontend]
    timeout-minutes: 45
    env:
      HTTPS_PROXY: http://proxy.hlag.com:11009
      HTTP_PROXY: http://proxy.hlag.com:11009
      NO_PROXY: 127.0.0.1,localhost,*.hlag.com
      NODE_EXTRA_CA_CERTS: C:\certs\corp-bundle.pem
      REQUESTS_CA_BUNDLE: C:\certs\corp-bundle.pem
      SSL_CERT_FILE: C:\certs\corp-bundle.pem
      NPM_CONFIG_STRICT_SSL: "false"           # keep to avoid TLS issues via Zscaler
      NPM_CONFIG_PROXY: http://proxy.hlag.com:11009
      NPM_CONFIG_HTTPS_PROXY: http://proxy.hlag.com:11009
      NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (v18) with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Write project .npmrc (proxy + registry)
        run: |
          @"
          proxy=$env:HTTPS_PROXY
          https-proxy=$env:HTTPS_PROXY
          strict-ssl=false
          registry=https://registry.npmjs.org/
          "@ | Out-File -FilePath "$env:GITHUB_WORKSPACE\.npmrc" -Encoding ascii

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}\node_modules
          key: node-modules-v5-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-v5-${{ runner.os }}-

      - name: Install dependencies
        run: |
          if (Test-Path package-lock.json) {
            npm ci --prefer-offline --no-audit --no-fund
          } else {
            npm install --include=dev --prefer-offline --no-audit --no-fund --legacy-peer-deps
          }

      # One-time fix for CRA/babel warning
      - name: Ensure Babel plugin present (only if missing)
        run: |
          if (-not (Test-Path "node_modules\@babel\plugin-proposal-private-property-in-object")) {
            npm install -D @babel/plugin-proposal-private-property-in-object --no-audit --no-fund --legacy-peer-deps
          }

      - name: Save node_modules cache
        if: always()
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}\node_modules
          key: node-modules-v5-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Build React app (don’t fail on warnings)
        run: |
          # Override GitHub's default CI=true so warnings don't stop the build
          $env:CI = ""
          # Disable CRA's ESLint in CI to avoid noisy false negatives
          $env:DISABLE_ESLINT_PLUGIN = "true"
          $env:REACT_APP_API_URL = "/api/"
          if (!(Test-Path ".\node_modules\.bin\react-scripts.cmd")) {
            throw "react-scripts missing from node_modules; install step did not complete correctly."
          }
          npm run build
          if (!(Test-Path "$env:GITHUB_WORKSPACE\build\index.html")) {
            throw "Build failed: build\index.html not found"
          }

      - name: Deploy to IIS site root
        run: |
          C:\deployments\scripts\deploy-frontend.ps1 -BuildDir "$env:GITHUB_WORKSPACE\build"
